### ISSUE TITLE
ur code is aids

### ISSUE THREAD

**Issue by 5Haze** [scoobyluvs/grabbed#1]
bro used a third party library to grab cookies lmfaooo

**Comment by scoobyluvs** [comment]
> bro used a third party library to grab cookies lmfaooo

@DonaldTrumpz when third party library is used 

https://previews.123rf.com/images/koya79/koya792006/koya79200600211/149749121-angry-emoji-isolated-on-yellow-background-mad-emoticon-3d-rendering.jpg
